{{- if eq .Values.global.storageLocation "on-cluster" }}
apiVersion: v1
kind: Service
metadata:
  name: drycc-storage-metanode-weed
  annotations:
    prometheus.io/path: /metrics
    prometheus.io/port: "9326"
    prometheus.io/scrape: "true"
    {{- with .Values.service.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  labels:
    heritage: drycc
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  selector:
    app: drycc-storage-metanode-weed
  ports:
  - name: s3
    port: 8333
    targetPort: 8333
    protocol: TCP
  - name: http
    port: 8888
    targetPort: 8888
    protocol: TCP
  - name: grpc
    port: 18888
    targetPort: 18888
    protocol: TCP
  - name: metrics
    port: 9326
    targetPort: 9326
    protocol: TCP
{{- end }}
