{{- if eq .Values.global.storageLocation "on-cluster" }}
{{- $replicaCount := int .Values.metanode.tikv.replicas }}
{{- $clusterDomain := .Values.global.clusterDomain }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: drycc-storage-metanode-tikv
  labels:
    heritage: drycc
  annotations:
    component.drycc.cc/version: {{ .Values.imageTag }}
spec:
  serviceName: drycc-storage-metanode-tikv
  replicas: {{ $replicaCount }}
  updateStrategy:
    type: RollingUpdate
  podManagementPolicy: Parallel
  selector:
    matchLabels:
      component: drycc-storage
      app: drycc-storage-metanode-tikv
  template:
    metadata:
      labels:
        component: drycc-storage
        app: drycc-storage-metanode-tikv
    spec:
      affinity:
        podAffinity: {{- include "common.affinities.pods" (dict "type" .Values.metanode.tikv.podAffinityPreset.type "component" "" "extraMatchLabels" .Values.metanode.tikv.podAffinityPreset.extraMatchLabels "topologyKey" "" "context" $) | nindent 10 }}
        podAntiAffinity: {{- include "common.affinities.pods" (dict "type" .Values.metanode.tikv.podAntiAffinityPreset.type "component" "" "extraMatchLabels" .Values.metanode.tikv.podAntiAffinityPreset.extraMatchLabels "topologyKey" "" "context" $) | nindent 10 }}
        nodeAffinity: {{- include "common.affinities.nodes" (dict "type" .Values.metanode.tikv.nodeAffinityPreset.type "key" .Values.metanode.tikv.nodeAffinityPreset.key "values" .Values.metanode.tikv.nodeAffinityPreset.values ) | nindent 10 }}
      serviceAccount: drycc-storage
      initContainers:
      - name: drycc-storage-metanode-weed-init
        image: registry.drycc.cc/drycc/python-dev:latest
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        args:
        - netcat
        - -v
        - -u
        - {{ include "mainnode.tipdUrls" . }}
      containers:
      - name: drycc-storage-metanode-tikv
        image: {{ .Values.imageRegistry }}/{{ .Values.imageOrg }}/storage:{{ .Values.imageTag }}
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        {{- if .Values.diagnosticMode.enabled }}
        command: {{- include "common.tplvalues.render" (dict "value" .Values.diagnosticMode.command "context" $) | nindent 10 }}
        args: {{- include "common.tplvalues.render" (dict "value" .Values.diagnosticMode.args "context" $) | nindent 10 }}
        {{- else }}
        args:
        - metanode
        - tikv
        - --pd-endpoints={{ include "mainnode.tipdUrls" . }}
        - --addr=0.0.0.0:20160
        - --status-addr=0.0.0.0:20180
        - --advertise-addr=$(POD_NAME).drycc-storage-metanode-tikv.$(NAMESPACE).svc.{{ $clusterDomain }}:20160
        - --advertise-status-addr=$(POD_NAME).drycc-storage-metanode-tikv.$(NAMESPACE).{{ $clusterDomain }}:20180
        - --data-dir=/data
        {{- end }}
        env:
        - name: TZ
          value: UTC
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        ports:
        - containerPort: 20160
        - containerPort: 20180
        {{- if not .Values.diagnosticMode.enabled }}
        startupProbe:
          httpGet:
            path: /metrics
            port: 20180
          initialDelaySeconds: 90
          periodSeconds: 5
          timeoutSeconds: 1
          successThreshold: 1
          failureThreshold: 5
        livenessProbe:
          tcpSocket:
            port: 20160
          initialDelaySeconds: 30
          periodSeconds: 5
          timeoutSeconds: 1
          successThreshold: 1
          failureThreshold: 5
        readinessProbe:
          tcpSocket:
            port: 20180
          initialDelaySeconds: 30
          periodSeconds: 5
          timeoutSeconds: 1
          successThreshold: 1
          failureThreshold: 5
        {{- end }}
        volumeMounts:
        - name: storage-config
          mountPath: /etc/seaweedfs
        - name: storage-metanode-tikv
          mountPath: /data
      volumes:
      - name: storage-config
        configMap:
          name: storage-config
      {{- if not (.Values.metanode.tikv.persistence.enabled) }}
      - name: storage-metanode-tikv
        emptyDir: {}
      {{- end }}
      securityContext:
        fsGroup: 1001
        runAsGroup: 1001
        runAsUser: 1001
  {{- if .Values.metanode.tikv.persistence.enabled }}
  volumeClaimTemplates:
  - metadata:
      name: storage-metanode-tikv
    spec:
      accessModes: [ "ReadWriteOnce" ]
      {{- if .Values.metanode.tikv.persistence.storageClass }}
      {{- if (eq "-" .Values.metanode.tikv.persistence.storageClass) }}
      storageClassName: ""
      {{- else }}
      storageClassName: "{{ .Values.metanode.tikv.persistence.storageClass }}"
      {{- end }}
      {{- end }}
      resources:
        requests:
          storage: {{ .Values.metanode.tikv.persistence.size | quote }}
  {{- end }}
{{- end }}
