{{- if eq .Values.global.storageLocation "on-cluster" }}
apiVersion: v1
kind: Service
metadata:
  name: drycc-storage-metanode-tikv
  annotations:
    prometheus.io/path: /metrics
    prometheus.io/port: "20180"
    prometheus.io/scrape: "true"
    {{- with .Values.service.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  labels:
    heritage: drycc
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  selector:
    app: drycc-storage-metanode-tikv
  ports:
  - name: addr
    port: 20160
    targetPort: 20160
    protocol: TCP
  - name: status
    port: 20180
    targetPort: 20180
    protocol: TCP
{{- end }}
