{{- if eq .Values.global.storageLocation "on-cluster" }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: drycc-storage-metanode
spec:
  podSelector:
    matchLabels:
      app: drycc-storage-metanode
  policyTypes:
    - Ingress
  ingress:
    - from:
      - namespaceSelector:
          matchLabels:
            kubernetes.io/metadata.name: {{ .Release.Namespace }}
{{- end }}
