{{- if eq .Values.global.storageLocation "on-cluster" }}
{{- $replicaCount := int .Values.metanode.weed.replicas }}
{{- $clusterDomain := .Values.global.clusterDomain }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: drycc-storage-metanode-weed
  labels:
    heritage: drycc
  annotations:
    component.drycc.cc/version: {{ .Values.imageTag }}
spec:
  serviceName: drycc-storage-metanode-weed
  replicas: {{ $replicaCount }}
  updateStrategy:
    type: RollingUpdate
  podManagementPolicy: Parallel
  selector:
    matchLabels:
      component: drycc-storage
      app: drycc-storage-metanode-weed
  template:
    metadata:
      labels:
        component: drycc-storage
        app: drycc-storage-metanode-weed
    spec:
      affinity:
        podAffinity: {{- include "common.affinities.pods" (dict "type" .Values.metanode.weed.podAffinityPreset.type "component" "" "extraMatchLabels" .Values.metanode.weed.podAffinityPreset.extraMatchLabels "topologyKey" "" "context" $) | nindent 10 }}
        podAntiAffinity: {{- include "common.affinities.pods" (dict "type" .Values.metanode.weed.podAntiAffinityPreset.type "component" "" "extraMatchLabels" .Values.metanode.weed.podAntiAffinityPreset.extraMatchLabels "topologyKey" "" "context" $) | nindent 10 }}
        nodeAffinity: {{- include "common.affinities.nodes" (dict "type" .Values.metanode.weed.nodeAffinityPreset.type "key" .Values.metanode.weed.nodeAffinityPreset.key "values" .Values.metanode.weed.nodeAffinityPreset.values ) | nindent 10 }}
      serviceAccount: drycc-storage
      initContainers:
      - name: drycc-storage-metanode-weed-init
        image: registry.drycc.cc/drycc/python-dev:latest
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        args:
        - netcat
        - -v
        - -a
        - {{ include "mainnode.weedUrls" . }}
      containers:
      - name: drycc-storage-metanode-weed
        image: {{ .Values.imageRegistry }}/{{ .Values.imageOrg }}/storage:{{ .Values.imageTag }}
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        args:
        - metanode
        - weed
        - -port=8888
        - -port.grpc=18888
        - -port.readonly=28888
        - -master={{ include "mainnode.weedUrls" . }}
        - -s3.port=8333
        - -defaultStoreDir=/data
        - -metricsPort=9326
        env:
        - name: TZ
          value: UTC
        ports:
        - containerPort: 8333
        - containerPort: 8888
        - containerPort: 9326
        - containerPort: 18888
        - containerPort: 28888
        startupProbe:
          httpGet:
            path: /metrics
            port: 9326
          initialDelaySeconds: 90
          periodSeconds: 5
          timeoutSeconds: 1
          successThreshold: 1
          failureThreshold: 5
        livenessProbe:
          tcpSocket:
            port: 8333
          initialDelaySeconds: 30
          periodSeconds: 5
          timeoutSeconds: 1
          successThreshold: 1
          failureThreshold: 5
        readinessProbe:
          tcpSocket:
            port: 8333
          initialDelaySeconds: 30
          periodSeconds: 5
          timeoutSeconds: 1
          successThreshold: 1
          failureThreshold: 5
        volumeMounts:
        - name: storage-config
          mountPath: /etc/seaweedfs
        {{- if .Values.metanode.weed.persistence.enabled }}
        - name: storage-metanode-weed
          mountPath: /data
        {{- end }}
      volumes:
      - name: storage-config
        configMap:
          name: storage-config
      securityContext:
        fsGroup: 1001
        runAsGroup: 1001
        runAsUser: 1001
  {{- if .Values.metanode.weed.persistence.enabled }}
  volumeClaimTemplates:
  - metadata:
      name: storage-metanode-weed
    spec:
      accessModes: [ "ReadWriteOnce" ]
      {{- if .Values.metanode.weed.persistence.storageClass }}
      {{- if (eq "-" .Values.metanode.weed.persistence.storageClass) }}
      storageClassName: ""
      {{- else }}
      storageClassName: "{{ .Values.metanode.weed.persistence.storageClass }}"
      {{- end }}
      {{- end }}
      resources:
        requests:
          storage: {{ .Values.metanode.weed.persistence.size | quote }}
  {{- end }}
{{- end }}
