{{- if eq .Values.global.storageLocation "on-cluster" }}
{{- $replicaCount := int .Values.mainnode.weed.replicas }}
{{- $clusterDomain := .Values.global.clusterDomain }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: drycc-storage-mainnode-weed
  labels:
    heritage: drycc
  annotations:
    component.drycc.cc/version: {{ .Values.imageTag }}
spec:
  serviceName: drycc-storage-mainnode-weed
  replicas: {{ $replicaCount }}
  updateStrategy:
    type: RollingUpdate
  podManagementPolicy: OrderedReady
  selector:
    matchLabels:
      component: drycc-storage
      app: drycc-storage-mainnode-weed
  template:
    metadata:
      labels:
        component: drycc-storage
        app: drycc-storage-mainnode-weed
    spec:
      affinity:
        podAffinity: {{- include "common.affinities.pods" (dict "type" .Values.mainnode.weed.podAffinityPreset.type "component" "" "extraMatchLabels" .Values.mainnode.weed.podAffinityPreset.extraMatchLabels "topologyKey" "" "context" $) | nindent 10 }}
        podAntiAffinity: {{- include "common.affinities.pods" (dict "type" .Values.mainnode.weed.podAntiAffinityPreset.type "component" "" "extraMatchLabels" .Values.mainnode.weed.podAntiAffinityPreset.extraMatchLabels "topologyKey" "" "context" $) | nindent 10 }}
        nodeAffinity: {{- include "common.affinities.nodes" (dict "type" .Values.mainnode.weed.nodeAffinityPreset.type "key" .Values.mainnode.weed.nodeAffinityPreset.key "values" .Values.mainnode.weed.nodeAffinityPreset.values ) | nindent 10 }}
      serviceAccount: drycc-storage
      containers:
      - name: drycc-storage-mainnode-weed
        image: {{ .Values.imageRegistry }}/{{ .Values.imageOrg }}/storage:{{ .Values.imageTag }}
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        args:
        - mainnode
        - weed
        - -mdir=/data
        - -ip=$(POD_NAME).drycc-storage-mainnode-weed.$(NAMESPACE).svc.{{ $clusterDomain }}
        - -port=9333
        - -port.grpc=19333
        - -peers={{ include "mainnode.weedUrls" . }}
        - -metricsPort=9324
        - -garbageThreshold={{ .Values.mainnode.weed.garbageThreshold }}
        - -defaultReplication={{ .Values.mainnode.weed.defaultReplication }}
        env:
        - name: TZ
          value: UTC
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        ports:
        - containerPort: 9333
        - containerPort: 19333
        - containerPort: 9324
        startupProbe:
          httpGet:
            path: /metrics
            port: 9324
          initialDelaySeconds: 90
          periodSeconds: 5
          timeoutSeconds: 1
          successThreshold: 1
          failureThreshold: 5
        livenessProbe:
          tcpSocket:
            port: 9333
          initialDelaySeconds: 30
          periodSeconds: 5
          timeoutSeconds: 1
          successThreshold: 1
          failureThreshold: 5
        readinessProbe:
          tcpSocket:
            port: 9333
          initialDelaySeconds: 30
          periodSeconds: 5
          timeoutSeconds: 1
          successThreshold: 1
          failureThreshold: 5
        volumeMounts:
        - name: storage-config
          mountPath: /etc/seaweedfs
        {{- if .Values.mainnode.weed.persistence.enabled }}
        - name: storage-mainnode-weed
          mountPath: /data
        {{- end }}
      volumes:
      - name: storage-config
        configMap:
          name: storage-config
      securityContext:
        fsGroup: 1001
        runAsGroup: 1001
        runAsUser: 1001
  {{- if .Values.mainnode.weed.persistence.enabled }}
  volumeClaimTemplates:
  - metadata:
      name: storage-mainnode-weed
    spec:
      accessModes: [ "ReadWriteOnce" ]
      {{- if .Values.mainnode.weed.persistence.storageClass }}
      {{- if (eq "-" .Values.mainnode.weed.persistence.storageClass) }}
      storageClassName: ""
      {{- else }}
      storageClassName: "{{ .Values.mainnode.weed.persistence.storageClass }}"
      {{- end }}
      {{- end }}
      resources:
        requests:
          storage: {{ .Values.mainnode.weed.persistence.size | quote }}
  {{- end }}
{{- end }}
