{{- if eq .Values.global.storageLocation "on-cluster" }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: drycc-storage-mainnode-weed-conjob
  labels:
    heritage: drycc
    app: drycc-storage-mainnode-weed-conjob
  annotations:
    component.drycc.cc/version: {{ .Values.imageTag }}
spec:
  timeZone: "{{ .Values.mainnode.cron.timeZone }}"
  schedule: "{{ .Values.mainnode.cron.schedule }}"
  concurrencyPolicy: "{{ .Values.mainnode.cron.concurrencyPolicy }}"
  successfulJobsHistoryLimit: {{ .Values.mainnode.cron.successfulJobsHistoryLimit }}
  failedJobsHistoryLimit: {{ .Values.mainnode.cron.failedJobsHistoryLimit }}
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: drycc-storage-mainnode-weed-conjob
        spec:
          restartPolicy: OnFailure
          serviceAccount: drycc-storage
          initContainers:
          - name: drycc-storage-mainnode-weed-init
            image: {{.Values.imageRegistry}}/{{.Values.imageOrg}}/python-dev:latest
            imagePullPolicy: {{.Values.imagePullPolicy}}
            args:
            - netcat
            - -v
            - -a
            - {{ include "mainnode.filerUrl" . }},{{ include "mainnode.weedUrls" . }}
          containers:
          - image: {{ .Values.imageRegistry }}/{{ .Values.imageOrg }}/storage:{{ .Values.imageTag }}
            imagePullPolicy: {{ .Values.imagePullPolicy }}
            name: drycc-storage-mainnode-weed-cronjob
            {{- if .Values.diagnosticMode.enabled }}
            command: {{- include "common.tplvalues.render" (dict "value" .Values.diagnosticMode.command "context" $) | nindent 14 }}
            args: {{- include "common.tplvalues.render" (dict "value" .Values.diagnosticMode.args "context" $) | nindent 14 }}
            {{- else }}
            args:
            - /usr/bin/env
            - bash
            - -ec
            - |
              # run weed shell
              echo -e "\n\\033[32m---> Start running audit cronjob <---\\033[0m\n"
              cat << EOF | weed shell -master={{ include "mainnode.weedUrls" . }} -filer={{ include "mainnode.filerUrl" . }}
              {{- (tpl .Values.mainnode.cron.scripts $) | nindent 14 -}}
              EOF
              echo -e "\n\\033[32m---> Audit cronjob run completed <---\\033[0m\n"
            {{- end }}
            env:
            - name: TZ
              value: UTC
{{- end }}
