{{- if eq .Values.global.storageLocation "on-cluster" }}
{{- $replicaCount := int .Values.mainnode.tipd.replicas }}
{{- $clusterDomain := .Values.global.clusterDomain }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: drycc-storage-mainnode-tipd
  labels:
    heritage: drycc
  annotations:
    component.drycc.cc/version: {{ .Values.imageTag }}
spec:
  serviceName: drycc-storage-mainnode-tipd
  replicas: {{ $replicaCount }}
  updateStrategy:
    type: RollingUpdate
  podManagementPolicy: OrderedReady
  selector:
    matchLabels:
      component: drycc-storage
      app: drycc-storage-mainnode-tipd
  template:
    metadata:
      labels:
        component: drycc-storage
        app: drycc-storage-mainnode-tipd
    spec:
      affinity:
        podAffinity: {{- include "common.affinities.pods" (dict "type" .Values.mainnode.tipd.podAffinityPreset.type "component" "" "extraMatchLabels" .Values.mainnode.tipd.podAffinityPreset.extraMatchLabels "topologyKey" "" "context" $) | nindent 10 }}
        podAntiAffinity: {{- include "common.affinities.pods" (dict "type" .Values.mainnode.tipd.podAntiAffinityPreset.type "component" "" "extraMatchLabels" .Values.mainnode.tipd.podAntiAffinityPreset.extraMatchLabels "topologyKey" "" "context" $) | nindent 10 }}
        nodeAffinity: {{- include "common.affinities.nodes" (dict "type" .Values.mainnode.tipd.nodeAffinityPreset.type "key" .Values.mainnode.tipd.nodeAffinityPreset.key "values" .Values.mainnode.tipd.nodeAffinityPreset.values ) | nindent 10 }}
      serviceAccount: drycc-storage
      containers:
      - name: drycc-storage-mainnode-tipd
        image: {{ .Values.imageRegistry }}/{{ .Values.imageOrg }}/storage:{{ .Values.imageTag }}
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        args:
        - mainnode
        - tipd
        - --name=$(POD_NAME)
        - --data-dir=/data
        - --client-urls=http://0.0.0.0:2379
        - --peer-urls=http://0.0.0.0:2380
        - --advertise-client-urls=http://$(POD_NAME).drycc-storage-mainnode-tipd.$(NAMESPACE).svc.{{ $clusterDomain }}:2379
        - --advertise-peer-urls=http://$(POD_NAME).drycc-storage-mainnode-tipd.$(NAMESPACE).svc.{{ $clusterDomain }}:2380
        env:
        - name: TZ
          value: UTC
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: DRYCC_STORAGE_TIPD_ENDPOINTS
          value: {{ include "mainnode.tipdUrls" . }}
        ports:
        - containerPort: 2379
        - containerPort: 2380
        startupProbe:
          httpGet:
            path: /metrics
            port: 2379
          initialDelaySeconds: 90
          periodSeconds: 5
          timeoutSeconds: 10
          successThreshold: 1
          failureThreshold: 5
        livenessProbe:
          tcpSocket:
            port: 2380
          initialDelaySeconds: 30
          periodSeconds: 5
          timeoutSeconds: 1
          successThreshold: 1
          failureThreshold: 5
        readinessProbe:
          tcpSocket:
            port: 2379
          initialDelaySeconds: 30
          periodSeconds: 5
          timeoutSeconds: 1
          successThreshold: 1
          failureThreshold: 5
        volumeMounts:
        - name: storage-config
          mountPath: /etc/seaweedfs
        {{- if .Values.mainnode.tipd.persistence.enabled }}
        - name: storage-mainnode-tipd
          mountPath: /data
        {{- end }}
      volumes:
      - name: storage-config
        configMap:
          name: storage-config
      securityContext:
        fsGroup: 1001
        runAsGroup: 1001
        runAsUser: 1001
  {{- if .Values.mainnode.tipd.persistence.enabled }}
  volumeClaimTemplates:
  - metadata:
      name: storage-mainnode-tipd
    spec:
      accessModes: [ "ReadWriteOnce" ]
      {{- if .Values.mainnode.tipd.persistence.storageClass }}
      {{- if (eq "-" .Values.mainnode.tipd.persistence.storageClass) }}
      storageClassName: ""
      {{- else }}
      storageClassName: "{{ .Values.mainnode.tipd.persistence.storageClass }}"
      {{- end }}
      {{- end }}
      resources:
        requests:
          storage: {{ .Values.mainnode.tipd.persistence.size | quote }}
  {{- end }}
{{- end }}
