apiVersion: v1
kind: Secret
metadata:
  name: drycc-storage-creds
  labels:
    heritage: drycc
type: Opaque
data:
  {{- if eq .Values.global.storageLocation "on-cluster"}}
  lookup: {{ "path" | b64enc }}
  {{- $endpoint := (printf "http://drycc-storage-metanode.%s.svc.%s:8333" .Release.Namespace .Values.global.clusterDomain) }}
  endpoint: {{ $endpoint | b64enc }}
  builder-bucket: {{ "builder" | b64enc }}
  registry-bucket: {{ "registry" | b64enc }}
  jwtkey: {{ if .Values.jwtkey | default "" | ne "" }}{{ .Values.jwtkey | b64enc }}{{ else }}{{ randAlphaNum 32 | b64enc }}{{ end }}
  {{- else }}
  lookup: {{ .Values.lookup | b64enc }}
  endpoint: {{ .Values.endpoint | b64enc }}
  builder-bucket: {{ .Values.builderBucket | b64enc }}
  registry-bucket: {{ .Values.registryBucket | b64enc }}
  {{- end }}
  accesskey: {{ if .Values.accesskey | default "" | ne "" }}{{ .Values.accesskey | b64enc }}{{ else }}{{ randAlphaNum 32 | b64enc }}{{ end }}
  secretkey: {{ if .Values.secretkey | default "" | ne "" }}{{ .Values.secretkey | b64enc }}{{ else }}{{ randAlphaNum 32 | b64enc }}{{ end }}
