apiVersion: v1
kind: Secret
metadata:
  name: drycc-storage-creds
  labels:
    heritage: drycc
type: Opaque
data:
  jwtkey: {{ if .Values.jwtkey | default "" | ne "" }}{{ .Values.jwtkey | b64enc }}{{ else }}{{ randAlphaNum 32 | b64enc }}{{ end }}
  accesskey: {{ if .Values.accesskey | default "" | ne "" }}{{ .Values.accesskey | b64enc }}{{ else }}{{ randAlphaNum 32 | b64enc }}{{ end }}
  secretkey: {{ if .Values.secretkey | default "" | ne "" }}{{ .Values.secretkey | b64enc }}{{ else }}{{ randAlphaNum 32 | b64enc }}{{ end }}
