{{- if eq .Values.global.storageLocation "on-cluster" }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: drycc-storage
spec:
  podSelector:
    matchLabels:
      component: drycc-storage
  policyTypes:
  - Ingress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: {{ .Release.Namespace }}
{{- end }}
