{{- if eq .Values.global.storageLocation "on-cluster" }}
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ printf "%s:drycc-storage" .Release.Namespace | quote }}
subjects:
- kind: ServiceAccount
  name: drycc-storage
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ printf "%s:drycc-storage" .Release.Namespace | quote }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}
