{{- if eq .Values.global.storageLocation "on-cluster" }}
apiVersion: storage.k8s.io/v1
kind: CSIDriver
metadata:
  name: {{ .Values.csi.driverName }}
spec:
  attachRequired: true
  podInfoOnMount: true
{{- end }}
