{{- if .Values.csi.storageClassName }}
{{- if eq .Values.global.storageLocation "on-cluster" }}
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: {{ .Values.csi.storageClassName }}
  annotations:
    component.drycc.cc/version: {{ .Values.imageTag }}
provisioner: {{ .Values.csi.driverName }}
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
{{- end }}
{{- end }}
