{{- if .Values.csi.storageClass.name }}
{{- if eq .Values.global.storageLocation "on-cluster" }}
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: {{ .Values.csi.storageClass.name }}
  annotations:
    component.drycc.cc/version: {{ .Values.imageTag }}
    {{ toYaml .Values.csi.storageClass.annotations | indent 4 }}
provisioner: {{ .Values.csi.driverName }}
allowVolumeExpansion: true
parameters:
  options: "{{ .Values.csi.storageClass.parameters.options }}"
  csi.storage.k8s.io/provisioner-secret-name: storage-creds
  csi.storage.k8s.io/provisioner-secret-namespace: {{ .Release.Namespace }}
  csi.storage.k8s.io/controller-publish-secret-name: storage-creds
  csi.storage.k8s.io/controller-publish-secret-namespace: {{ .Release.Namespace }}
  csi.storage.k8s.io/controller-expand-secret-name: storage-creds
  csi.storage.k8s.io/controller-expand-secret-namespace: {{ .Release.Namespace }}
  csi.storage.k8s.io/node-stage-secret-name: storage-creds
  csi.storage.k8s.io/node-stage-secret-namespace: {{ .Release.Namespace }}
  csi.storage.k8s.io/node-publish-secret-name: storage-creds
  csi.storage.k8s.io/node-publish-secret-namespace: {{ .Release.Namespace }}
reclaimPolicy: {{ .Values.csi.storageClass.reclaimPolicy }}
volumeBindingMode: WaitForFirstConsumer
{{- end }}
{{- end }}
