{{- if eq .Values.global.storageLocation "on-cluster" }}
apiVersion: storage.k8s.io/v1
kind: CSIDriver
metadata:
  name: drycc-storage-csi
spec:
  attachRequired: true
  podInfoOnMount: true
{{- end }}
