
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: drycc-storage-csi
  namespace: {{ .Release.Namespace }}
rules:
  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    verbs: ["get", "watch", "list", "delete", "update", "create"]
