{{- if eq .Values.global.storageLocation "on-cluster" }}
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: drycc-storage-csi
subjects:
  - kind: ServiceAccount
    name: drycc-storage-csi
    namespace: default
roleRef:
  kind: ClusterRole
  name: drycc:drycc-storage-csi
  apiGroup: rbac.authorization.k8s.io
{{- end }}
